### PR TITLE
Update epiphany to 44.0

### LINKED ISSUE #6: Update epiphany snap to 44
Epiphany 44 switched to webkitgtk-6.0 which is a GTK4 build of webkit2gtk. As of April 11, 2023, Ubuntu 22.04 LTS does not include a GTK4 build for webkit2gtk so either that will [need to be done](https://launchpad.net/bugs/2015923) or we need to have the Epiphany snap build webkitgtk itself. That would significantly increase the build time (although we would only need to build the gtk4 version instead of the two gtk3 versions that the Ubuntu .deb also needs to build).

### PR DESCRIPTION
**Pull request by sergio-costas**
This is still a work-in-progress:

- to build it, a manual "apt update" must be done inside the build environment
- the audio still doesn't work

Fix https://github.com/ubuntu/epiphany/issues/6

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please check only the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

**Test Configuration**:

* OS (please include version):
* Any other relevant environment information:

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by jbicha** [comment]
This snap update passes my basic manual tests.

By the way, the latest 44.x version is 44.6, but the automation would pick that up.

**Comment by sergio-costas** [comment]
@jbicha If you open a youtube video, does it work with sound?

**Comment by jbicha** [comment]
Yes. I have sound in the sample YouTube video. My host OS is Ubuntu "Mantic"

**Comment by sergio-costas** [comment]
I tried with 44.6, but still no sound... This is odd. Have you tried to do a "snapcraft clean" before?

**Comment by jbicha** [comment]
Yes, but I used the Artifact produced on the Checks tab at https://github.com/ubuntu/epiphany/pull/10

**Comment by sergio-costas** [comment]
@jbicha This is even more odd... I tried that snap, and it still doesn't have audio.

**Comment by sergio-costas** [comment]
Just in case... Can you check if you have the .deb version installed?

**Comment by jbicha** [comment]
> Just in case... Can you check if you have the .deb version installed?

I did. But I've uninstalled it now and the sound worked.

So then I installed Ubuntu 23.10 Beta (default install, didn't check boxes to install anything extra) in GNOME Boxes and then installed the epiphany snap from this CI run and sound worked for me with a YouTube video.

**Comment by sergio-costas** [comment]
I'm really puzzled...

**Comment by kenvandine** [comment]
The snap built in the CI build worked fine for me, including audio in youtube.  I think it's worth landing this so we can let the automation bump it to the latest.

**Comment by sergio-costas** [comment]
Ok, now it seems to work even in my system... odd.

**Comment by sergio-costas** [comment]
It seems that epiphany 45 can't be built with core22...

:: ../src/meson.build:111:16: ERROR: Dependency lookup for webkitgtk-6.0 with method 'pkgconfig' failed: Invalid version, need 'webkitgtk-6.0' ['>= 2.41.1'] found '2.40.5'.

**Comment by jbicha** [comment]
@sergio-costas webkit2gtk 2.42 landed in Ubuntu 22.04 LTS this week. Once the GNOME SDK is updated for that, you should be able to update Epiphany to 45.0

**Comment by jbicha** [comment]
Epiphany 45.0 is already in the repository and was pushed to the stable channel earlier.

**Pull request closed without merging**
